name: Playwright test reusable workflow

on:
  workflow_call:
    inputs:
      shard:
        description: "Shard number"
        required: true
        type: string
      db:
        required: true
        type: string

jobs:
  playwright:
    runs-on: ubuntu-22.04
    timeout-minutes: 100
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: remove use-node-version from .npmrc
        run: sed -i '/^use-node-version/d' .npmrc
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.3
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: setup pg
        working-directory: ./
        run: |
          docker compose -f ./tests/playwright/scripts/docker-compose-playwright-pg.yml up -d
      - name: Set CI env
        run: export CI=true
      - name: Set NC Edition
        run: export EE=false
      - name: install dependencies
        run: pnpm bootstrap
      - name: Run backend:pg
        working-directory: ./packages/nocodb
        run: |
          pnpm run watch:run:playwright:pg &> ${{ inputs.db }}_${{ inputs.shard }}_test_backend.log &
      - name: Restore frontend build
        uses: actions/cache/restore@v4
        with:
          path: ./packages/nc-gui/.output/
          key: nc-gui-build-${{ github.run_id }}
          fail-on-cache-miss: true
      - name: start frontend
        working-directory: ./packages/nc-gui/
        run: |
          pnpm run ci:start
      - name: Install Playwright Browsers
        working-directory: ./tests/playwright
        run: pnpm exec playwright install --with-deps chromium
      - name: Wait for frontend and backend
        run: |
          while ! curl --output /dev/null --silent --head --fail http://localhost:3000; do
            printf '.'
            sleep 2
          done
          echo "Frontend is up"
          while ! curl --output /dev/null --silent --head --fail http://localhost:8080; do
            printf '.'
            sleep 2
          done
          echo "Backend is up"
        timeout-minutes: 5
      - name: Run Playwright Tests
        working-directory: ./tests/playwright
        run: E2E_DB_TYPE=${{ inputs.db }} npm run ci:test:shard:${{ inputs.shard }}
        timeout-minutes: 60
      # Stress test added/modified tests
      - name: Fetch develop branch
        working-directory: ./tests/playwright
        run: git fetch origin develop
      - name: Stress test
        working-directory: ./tests/playwright
        run: E2E_DB_TYPE=${{ inputs.db }} node ./scripts/stressTestNewlyAddedTest.js

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ inputs.db }}-${{ inputs.shard }}
          path: ./tests/playwright/playwright-report/
          retention-days: 2
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-stress-${{ inputs.db }}-${{ inputs.shard }}
          path: ./tests/playwright/playwright-report-stress/
          retention-days: 2
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-logs-${{ inputs.db }}-${{ inputs.shard }}
          path: ./packages/nocodb/${{ inputs.db }}_${{ inputs.shard }}_test_backend.log
          retention-days: 2
      - name: Stop database containers
        if: always()
        run: |
          docker compose -f ./tests/playwright/scripts/docker-compose-playwright-pg.yml down
